# Proyek Akhir: Pengembangan dan Pengoperasian Sistem Machine Learning



**Dataset:** Chicago Taxi Trips

**Persoalan:** Memprediksi apakah seorang penumpang taxi akan memberikan tip atau tidak berdasarkan data perjalanan.

---

## 1. Informasi Dataset

Dataset yang digunakan adalah **Chicago Taxi Trips** yang merupakan dataset publik dari kota Chicago, Illinois, Amerika Serikat. Dataset ini berisi informasi tentang perjalanan taksi yang dilakukan di kota Chicago.

### Fitur-fitur dalam dataset:
| Fitur | Tipe | Deskripsi |
|-------|------|-----------|
| trip_start_month | Integer | Bulan dimulainya perjalanan |
| trip_start_hour | Integer | Jam dimulainya perjalanan |
| trip_start_day | Integer | Hari dimulainya perjalanan |
| trip_start_timestamp | Integer | Timestamp dimulainya perjalanan |
| pickup_latitude | Float | Latitude lokasi penjemputan |
| pickup_longitude | Float | Longitude lokasi penjemputan |
| dropoff_latitude | Float | Latitude lokasi penurunan |
| dropoff_longitude | Float | Longitude lokasi penurunan |
| trip_miles | Float | Jarak perjalanan (mil) |
| trip_seconds | Float | Durasi perjalanan (detik) |
| fare | Float | Tarif perjalanan |
| tips | Float | Jumlah tip (label/target) |
| payment_type | String | Metode pembayaran |
| company | String | Perusahaan taksi |
| pickup_community_area | Integer | Area komunitas penjemputan |
| dropoff_community_area | Integer | Area komunitas penurunan |

## 2. Persoalan yang Ingin Diselesaikan

### Latar Belakang
Dalam industri transportasi, memahami faktor-faktor yang memengaruhi pemberian tip oleh penumpang dapat membantu pengemudi dan perusahaan taksi dalam meningkatkan kualitas layanan dan pendapatan.

### Problem Statement
Membangun sistem machine learning yang dapat memprediksi apakah seorang penumpang akan memberikan tip berdasarkan karakteristik perjalanan taksi.

### Tujuan
- Mengembangkan model prediksi yang akurat untuk memprediksi pemberian tip
- Mengimplementasikan MLOps pipeline end-to-end menggunakan TFX
- Menjalankan sistem di cloud dengan monitoring menggunakan Prometheus

## 3. Solusi Machine Learning

### Pendekatan
Masalah ini adalah **klasifikasi biner** (binary classification) dimana targetnya adalah apakah penumpang memberikan tip (`tips > 0`) atau tidak.

### Target
- **1**: Penumpang memberikan tip (tips > 0)
- **0**: Penumpang tidak memberikan tip (tips = 0)

### Metode Pengolahan Data
1. **Scaling numerik**: Fitur numerik (trip_miles, fare, trip_seconds) di-scale menggunakan Z-score
2. **Feature engineering**: Membuat fitur baru `trip_speed` (trip_miles / trip_seconds)
3. **Encoding kategorikal**: Fitur kategorikal di-encode menggunakan vocab mapping
4. **Label biner**: Kolom `tips` dikonversi menjadi label biner (0/1)

### Arsitektur Model
- Input layer untuk fitur numerik dan kategorikal
- Embedding layer untuk fitur kategorikal
- Dense layers: [64, 32] dengan aktivasi ReLU
- Dropout 20% untuk regularisasi
- Output layer: 1 neuron dengan sigmoid activation

### Metrik Evaluasi
- **Binary Accuracy**: Akurasi prediksi
- **AUC**: Performa model secara keseluruhan
- **Precision**: Ketepatan prediksi positif
- **Recall**: Sensitivitas model

## 4. Import Library dan Setup Environment

In [1]:
import os
import sys
import logging

import tensorflow as tf
import pandas as pd

from tfx.orchestration.beam.beam_dag_runner import BeamDagRunner

logging.basicConfig(level=logging.INFO)

print(f"TensorFlow version: {tf.__version__}")
print(f"Python version: {sys.version}")

PROJECT_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

print(f"Project directory: {PROJECT_DIR}")

2026-05-31 10:57:49.993102: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-31 10:57:50.000364: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-05-31 10:57:50.026751: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-05-31 10:57:50.079265: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-05-31 10:57:50.079342: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-05-31 10:57:50.113962: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

/home/sintiawati_putu04/miniconda/envs/sintiawati-pipeline/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

2026-05-31 10:57:52.284169: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

/home/sintiawati_putu04/miniconda/envs/sintiawati-pipeline/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.cloud.bigquery_storage_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.bigquery_storage_v1 past that date.
  warnings.warn(message, FutureWarning)

/home/sintiawati_putu04/miniconda/envs/sintiawati-pipeline/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.pubsub_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.pubsub_v1 past that date.
  warnings.warn(message, FutureWarning)

TensorFlow version: 2.16.2
Python version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]
Project directory: /home/user/chicago-taxi-mlops

## 5. Eksplorasi Data

In [2]:
DATA_PATH = "data/data.csv"
df = pd.read_csv(DATA_PATH)
print(f"Dataset shape: {df.shape}")
print(f"\nFirst 5 rows:")
df.head()

Dataset shape: (15002, 18)

First 5 rows:

,pickup_community_area,fare,trip_start_month,trip_start_hour,trip_start_day,trip_start_timestamp,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude,trip_miles,pickup_census_tract,dropoff_census_tract,payment_type,company,trip_seconds,dropoff_community_area,tips
0,0,12.45,5,19,6,1400269500,0.000000,0.000000,0.0,0.0,0.0,0,0,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,0,0,0.0
1,0,0.00,3,19,5,1362683700,0.000000,0.000000,0.0,0.0,0.0,0,0,Unknown,Chicago Elite Cab Corp.,300,0,0.0
2,60,27.05,10,2,3,1380593700,41.836150,-87.648788,0.0,0.0,12.6,0,0,Cash,Taxi Affiliation Services,1380,0,0.0
3,10,5.85,10,1,2,1382319000,41.985015,-87.804532,0.0,0.0,0.0,0,0,Cash,Taxi Affiliation Services,180,0,0.0
4,14,16.65,5,7,5,1369897200,41.968069,-87.721559,0.0,0.0,0.0,0,0,Cash,Dispatch Taxi Affiliation,1080,0,0.0

In [3]:
print("Dataset Info:")
df.info()

Dataset Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15002 entries, 0 to 15001
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pickup_community_area   15002 non-null  int64
 1   fare                    15002 non-null  float64
 2   trip_start_month        15002 non-null  int64
 3   trip_start_hour         15002 non-null  int64
 4   trip_start_day          15002 non-null  int64
 5   trip_start_timestamp    15002 non-null  int64
 6   pickup_latitude         15002 non-null  float64
 7   pickup_longitude        15002 non-null  float64
 8   dropoff_latitude        15002 non-null  float64
 9   dropoff_longitude       15002 non-null  float64
 10  trip_miles              15002 non-null  float64
 11  pickup_census_tract     15002 non-null  int64
 12  dropoff_census_tract    15002 non-null  int64
 13  payment_type            15002 non-null  object
 14  company                 15002 non-null  object
 15  trip_seconds            15002 non-null  int64
 16  dropoff_community_area  15002 non-null  int64
 17  tips                    15002 non-null  float64
dtypes: float64(7), int64(9), object(2)
memory usage: 2.1+ MB

In [4]:
print("Descriptive Statistics:")
df.describe()

Descriptive Statistics:

,pickup_community_area,fare,trip_start_month,trip_start_hour,trip_start_day,trip_start_timestamp,pickup_latitude,pickup_longitude,dropoff_latitude,dropoff_longitude,trip_miles,pickup_census_tract,dropoff_census_tract,trip_seconds,dropoff_community_area,tips
count,15002.000000,15002.000000,15002.000000,15002.000000,15002.000000,1.500200e+04,15002.000000,15002.000000,15002.000000,15002.000000,15002.000000,1.500200e+04,1.500200e+04,15002.000000,15002.000000,15002.000000
mean,22.247300,11.768216,6.585655,13.632316,4.186642,1.408495e+09,41.897459,-87.645865,40.553586,-84.832027,2.872820,1.135254e+06,1.221666e+10,777.316491,20.259165,1.076674
std,19.415234,11.538850,3.390997,6.620927,2.015694,2.916043e+07,0.485277,1.014352,7.396983,15.473279,15.276007,1.390489e+08,7.669635e+09,977.466933,17.749526,2.158340
min,0.000000,0.000000,1.000000,0.000000,1.000000,1.357000e+09,0.000000,-87.913625,0.000000,-87.913625,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000
25%,8.000000,5.850000,4.000000,9.000000,2.000000,1.384622e+09,41.880994,-87.655998,41.880994,-87.655998,0.000000,0.000000e+00,0.000000e+00,360.000000,8.000000,0.000000
50%,8.000000,7.850000,7.000000,15.000000,4.000000,1.407260e+09,41.892508,-87.633308,41.892508,-87.633308,1.000000,0.000000e+00,1.703108e+10,540.000000,8.000000,0.000000
75%,32.000000,12.450000,10.000000,19.000000,6.000000,1.431339e+09,41.921872,-87.626211,41.922031,-87.626211,2.500000,0.000000e+00,1.703132e+10,960.000000,32.000000,2.000000
max,77.000000,700.070000,12.000000,23.000000,7.000000,1.483116e+09,42.009623,0.000000,42.021224,0.000000,1710.000000,1.703108e+10,1.703198e+10,72120.000000,77.000000,47.000000

In [5]:
print("Label Distribution (tips > 0):")
df["tips_binary"] = (df["tips"] > 0).astype(int)
print(df["tips_binary"].value_counts())
print(f"\nPercentage:")
print(df["tips_binary"].value_counts(normalize=True) * 100)

Label Distribution (tips > 0):
0    10259
1     4743
Name: tips_binary, dtype: int64

Percentage:

0    68.384215
1    31.615785
Name: tips_binary, dtype: float64

In [6]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

pickup_community_area     0
fare                      0
trip_start_month          0
trip_start_hour           0
trip_start_day            0
trip_start_timestamp      0
pickup_latitude           0
pickup_longitude          0
dropoff_latitude          0
dropoff_longitude         0
trip_miles                0
pickup_census_tract       0
dropoff_census_tract      0
payment_type              0
company                   0
trip_seconds              0
dropoff_community_area    0
tips                      0
tips_binary               0
dtype: int64

## 6. Menjalankan TFX Pipeline

Pipeline akan menjalankan seluruh komponen:
1. **ExampleGen**: Memuat dan membagi dataset
2. **StatisticsGen**: Menghasilkan statistik data
3. **SchemaGen**: Membuat skema data
4. **ExampleValidator**: Memvalidasi data
5. **Transform**: Mentransformasi data
6. **Trainer**: Melatih model
7. **Resolver**: Mendapatkan model terbaik sebelumnya
8. **Evaluator**: Mengevaluasi model
9. **Pusher**: Mempush model ke serving

In [7]:
%%time
from taxi_pipeline.pipeline_def import create_pipeline

pipeline = create_pipeline()
BeamDagRunner().run(pipeline)
print("Pipeline execution completed!")

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:ArtifactQuery.property_predicate is not supported.

Trial 3 Complete [00h 00m 27s]
val_auc: 0.5

Best val_auc So Far: 0.5
Total elapsed time: 00h 01m 05s
Results summary
Results in /home/user/chicago-taxi-mlops/output/pipeline_root/Tuner/.system/executor_execution/73/.temp/73/taxi_tip_tuning
Showing 10 best trials
Objective(name="val_auc", direction="max")

Trial 0 summary
Hyperparameters:
units_1: 64
units_2: 64
dropout_rate: 0.30000000000000004
learning_rate: 0.001
Score: 0.5

Trial 1 summary
Hyperparameters:
units_1: 128
units_2: 128
dropout_rate: 0.2
learning_rate: 0.001
Score: 0.5

Trial 2 summary
Hyperparameters:
units_1: 256
units_2: 128
dropout_rate: 0.4
learning_rate: 0.0001
Score: 0.5

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

Processing ./output/pipeline_root/_wheels/tfx_user_code_trainer-0.0+9ce7107b01410c5b84004ec5dfc6697c8e3446acf24b8eecd2fe598b8e170ee5-py3-none-any.whl

Installing collected packages: tfx-user-code-trainer
Successfully installed tfx-user-code-trainer-0.0+9ce7107b01410c5b84004ec5dfc6697c8e3446acf24b8eecd2fe598b8e170ee5

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ payment_type_xf     │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ company_xf          │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_start_hour_xf  │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_start_day_xf   │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_start_month_xf │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_miles_xf       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ fare_xf             │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_seconds_xf     │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_start_timesta… │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ trip_speed_xf       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_payment_… │ (None, 1, 8)      │         64 │ payment_type_xf[… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_company   │ (None, 1, 8)      │        456 │ company_xf[0][0]  │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_trip_sta… │ (None, 1, 8)      │        232 │ trip_start_hour_… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_trip_sta… │ (None, 1, 8)      │         96 │ trip_start_day_x… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_trip_sta… │ (None, 1, 8)      │        136 │ trip_start_month… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_2       │ (None, 5)         │          0 │ trip_miles_xf[0]… │
│ (Concatenate)       │                   │            │ fare_xf[0][0],    │
│                     │                   │            │ trip_seconds_xf[… │
│                     │                   │            │ trip_start_times… │
│                     │                   │            │ trip_speed_xf[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_5 (Flatten) │ (None, 8)         │          0 │ embedding_paymen… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_6 (Flatten) │ (None, 8)         │          0 │ embedding_compan… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_7 (Flatten) │ (None, 8)         │          0 │ embedding_trip_s… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_8 (Flatten) │ (None, 8)         │          0 │ embedding_trip_s… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_9 (Flatten) │ (None, 8)         │          0 │ embedding_trip_s… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_3       │ (None, 45)        │          0 │ concatenate_2[0]… │
│ (Concatenate)       │                   │            │ flatten_5[0][0],  │
│                     │                   │            │ flatten_6[0][0],  │
│                     │                   │            │ flatten_7[0][0],  │
│                     │                   │            │ flatten_8[0][0],  │
│                     │                   │            │ flatten_9[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 64)        │      2,944 │ concatenate_3[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 64)        │          0 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 64)        │      4,160 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 64)        │          0 │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 1)         │         65 │ dropout_3[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 8,153 (31.85 KB)

 Trainable params: 8,153 (31.85 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10

  1/500 ━━━━━━━━━━━━━━━━━━━━ 37:41 5s/step - auc: 0.5275 - binary_accuracy: 0.6562 - loss: 40050168.0000

  5/500 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - auc: 0.4975 - binary_accuracy: 0.5991 - loss: 47403593.6000

  9/500 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - auc: 0.5027 - binary_accuracy: 0.5863 - loss: 46847057.7778

 15/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.5041 - binary_accuracy: 0.5752 - loss: 46446006.4000

 20/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.5042 - binary_accuracy: 0.5702 - loss: 45599960.2000

 25/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5036 - binary_accuracy: 0.5672 - loss: 44632243.3600

 29/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.5030 - binary_accuracy: 0.5658 - loss: 43839238.4828

 34/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.5041 - binary_accuracy: 0.5654 - loss: 42813257.8824

 39/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5054 - binary_accuracy: 0.5648 - loss: 41841505.5385

 44/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5060 - binary_accuracy: 0.5639 - loss: 40943170.0455

 49/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5064 - binary_accuracy: 0.5633 - loss: 40073844.6122

 54/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5064 - binary_accuracy: 0.5623 - loss: 39259785.6667

 59/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5062 - binary_accuracy: 0.5613 - loss: 38494859.0508

 65/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5062 - binary_accuracy: 0.5607 - loss: 37599453.5385

 71/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5062 - binary_accuracy: 0.5605 - loss: 36735596.1408

 76/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5063 - binary_accuracy: 0.5605 - loss: 36041870.2105

 82/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5063 - binary_accuracy: 0.5606 - loss: 35245490.3902

 88/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5065 - binary_accuracy: 0.5607 - loss: 34485913.6591

 93/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5066 - binary_accuracy: 0.5609 - loss: 33878365.3548

 99/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5068 - binary_accuracy: 0.5610 - loss: 33181342.3030

104/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5069 - binary_accuracy: 0.5610 - loss: 32626000.7115

109/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5070 - binary_accuracy: 0.5610 - loss: 32089809.9633

114/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5069 - binary_accuracy: 0.5610 - loss: 31571359.2281

120/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5069 - binary_accuracy: 0.5609 - loss: 30972685.3167

125/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5067 - binary_accuracy: 0.5609 - loss: 30492557.6480

130/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5066 - binary_accuracy: 0.5608 - loss: 30027465.7538

136/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5064 - binary_accuracy: 0.5607 - loss: 29488508.6176

142/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5063 - binary_accuracy: 0.5607 - loss: 28969970.5211

147/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5062 - binary_accuracy: 0.5607 - loss: 28552480.3333

152/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5607 - loss: 28147587.6974

158/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5607 - loss: 27677842.0949

163/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5607 - loss: 27299271.3129

168/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5608 - loss: 26931476.9881

173/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5609 - loss: 26574363.4624

176/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5609 - loss: 26364920.5852

181/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5611 - loss: 26023466.9945

187/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5612 - loss: 25626181.1016

192/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5614 - loss: 25304985.0573

197/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5616 - loss: 24992353.4670

203/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5057 - binary_accuracy: 0.5618 - loss: 24628273.8473

210/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5621 - loss: 24217746.3238

215/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5623 - loss: 23933462.8233

221/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5625 - loss: 23601837.9457

227/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5628 - loss: 23280112.2775

232/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5629 - loss: 23019366.4009

238/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5631 - loss: 22714915.0924

244/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5633 - loss: 22419200.0738

250/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5636 - loss: 22131877.5640

255/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5637 - loss: 21898607.7804

261/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5639 - loss: 21625778.6935

267/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5641 - loss: 21360370.6030

272/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5642 - loss: 21144780.4081

277/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5643 - loss: 20934077.3646

283/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5061 - binary_accuracy: 0.5645 - loss: 20687352.1625

289/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5646 - loss: 20447058.1246

295/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5647 - loss: 20212938.2814

300/500 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - auc: 0.5060 - binary_accuracy: 0.5648 - loss: 20022389.6033

306/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5649 - loss: 19799008.6275

311/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5059 - binary_accuracy: 0.5650 - loss: 19617077.5370

316/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5650 - loss: 19438845.2674

321/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5058 - binary_accuracy: 0.5651 - loss: 19264222.5935

326/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5057 - binary_accuracy: 0.5652 - loss: 19093098.4801

331/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5057 - binary_accuracy: 0.5653 - loss: 18925347.2311

336/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5056 - binary_accuracy: 0.5654 - loss: 18760888.3229

340/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5056 - binary_accuracy: 0.5655 - loss: 18631641.2397

344/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5055 - binary_accuracy: 0.5655 - loss: 18504373.2267

350/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5055 - binary_accuracy: 0.5657 - loss: 18317076.9971

356/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5055 - binary_accuracy: 0.5658 - loss: 18133997.1419

361/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5054 - binary_accuracy: 0.5659 - loss: 17984547.3795

367/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5054 - binary_accuracy: 0.5660 - loss: 17808839.6281

372/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5054 - binary_accuracy: 0.5661 - loss: 17665329.3495

377/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5053 - binary_accuracy: 0.5661 - loss: 17524391.0133

382/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5053 - binary_accuracy: 0.5662 - loss: 17385960.2736

386/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5053 - binary_accuracy: 0.5663 - loss: 17276967.2642

391/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5052 - binary_accuracy: 0.5664 - loss: 17142875.3465

396/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5052 - binary_accuracy: 0.5665 - loss: 17011113.3851

401/500 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - auc: 0.5052 - binary_accuracy: 0.5666 - loss: 16881623.9564

406/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5052 - binary_accuracy: 0.5667 - loss: 16754367.1909

410/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5052 - binary_accuracy: 0.5668 - loss: 16654108.7024

416/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5669 - loss: 16506226.6791

421/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5670 - loss: 16385245.4252

426/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5671 - loss: 16266255.9261

431/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5672 - loss: 16149208.4803

436/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5673 - loss: 16034040.8234

442/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5051 - binary_accuracy: 0.5675 - loss: 15898260.0283

447/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5050 - binary_accuracy: 0.5676 - loss: 15787087.0257

453/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5050 - binary_accuracy: 0.5677 - loss: 15655968.0121

458/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5050 - binary_accuracy: 0.5678 - loss: 15548565.6157

462/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5050 - binary_accuracy: 0.5679 - loss: 15463834.7457

468/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5050 - binary_accuracy: 0.5680 - loss: 15338698.4167

473/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5049 - binary_accuracy: 0.5681 - loss: 15236160.9915

477/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5049 - binary_accuracy: 0.5682 - loss: 15155238.2023

482/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5049 - binary_accuracy: 0.5683 - loss: 15055440.2075

488/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5049 - binary_accuracy: 0.5684 - loss: 14937628.7449

493/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5049 - binary_accuracy: 0.5685 - loss: 14841034.4128

499/500 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - auc: 0.5048 - binary_accuracy: 0.5686 - loss: 14726980.5140

500/500 ━━━━━━━━━━━━━━━━━━━━ 11s 13ms/step - auc: 0.5027 - binary_accuracy: 0.5792 - loss: 5319019.0000 - val_auc: 0.5000 - val_binary_accuracy: 0.3072 - val_loss: 216.4868

Epoch 2/10

  1/500 ━━━━━━━━━━━━━━━━━━━━ 7s 15ms/step - auc: 0.5119 - binary_accuracy: 0.5000 - loss: 32678.7109

  6/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.5016 - binary_accuracy: 0.5641 - loss: 51315.7487

 11/500 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - auc: 0.5010 - binary_accuracy: 0.5797 - loss: 58368.1538

2026-05-31 11:00:22.321281: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

 14/500 ━━━━━━━━━━━━━━━━━━━━ 6s 14ms/step - auc: 0.5004 - binary_accuracy: 0.5809 - loss: 61448.6766

 20/500 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - auc: 0.4991 - binary_accuracy: 0.5791 - loss: 64661.6955

 25/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4978 - binary_accuracy: 0.5768 - loss: 67641.8783

 30/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4977 - binary_accuracy: 0.5756 - loss: 70289.9530

 35/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4987 - binary_accuracy: 0.5769 - loss: 72544.6450

 40/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4991 - binary_accuracy: 0.5770 - loss: 75573.4253

 45/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4996 - binary_accuracy: 0.5774 - loss: 78138.5445

 50/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4996 - binary_accuracy: 0.5776 - loss: 80808.0571

 56/500 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - auc: 0.4998 - binary_accuracy: 0.5780 - loss: 83141.0217

 62/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4995 - binary_accuracy: 0.5784 - loss: 85781.8674

 67/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4992 - binary_accuracy: 0.5783 - loss: 87906.5252

 72/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4989 - binary_accuracy: 0.5783 - loss: 89578.6023

 77/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4989 - binary_accuracy: 0.5785 - loss: 90654.2788

 82/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4989 - binary_accuracy: 0.5789 - loss: 91366.1722

 87/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4992 - binary_accuracy: 0.5794 - loss: 91790.4409

 92/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4995 - binary_accuracy: 0.5800 - loss: 92014.5602

 97/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4997 - binary_accuracy: 0.5806 - loss: 92284.3208

102/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4999 - binary_accuracy: 0.5812 - loss: 92509.8496

107/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5002 - binary_accuracy: 0.5818 - loss: 92605.9665

112/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5004 - binary_accuracy: 0.5826 - loss: 92631.3639

118/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5007 - binary_accuracy: 0.5833 - loss: 92637.8199

123/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5009 - binary_accuracy: 0.5839 - loss: 92515.4344

127/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5011 - binary_accuracy: 0.5844 - loss: 92354.5187

131/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5847 - loss: 92165.4324

136/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5852 - loss: 91970.5187

141/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5856 - loss: 91868.4080

145/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5859 - loss: 91802.5591

150/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5015 - binary_accuracy: 0.5862 - loss: 91756.1842

155/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5015 - binary_accuracy: 0.5865 - loss: 91678.3267

160/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5016 - binary_accuracy: 0.5868 - loss: 91563.4519

166/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5872 - loss: 91363.1620

171/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5874 - loss: 91150.1226

176/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5877 - loss: 90908.8394

181/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5879 - loss: 90651.7410

186/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5882 - loss: 90355.7360

191/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5017 - binary_accuracy: 0.5884 - loss: 90050.3078

196/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5016 - binary_accuracy: 0.5886 - loss: 89766.2268

201/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5016 - binary_accuracy: 0.5887 - loss: 89502.3231

206/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5015 - binary_accuracy: 0.5889 - loss: 89269.1601

211/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5015 - binary_accuracy: 0.5891 - loss: 89045.0962

217/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5893 - loss: 88765.0272

221/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5895 - loss: 88563.2506

227/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5897 - loss: 88250.1212

232/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5899 - loss: 87972.4963

237/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5901 - loss: 87680.0576

242/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5903 - loss: 87384.8418

247/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5905 - loss: 87107.8307

253/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5907 - loss: 86773.9737

258/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5012 - binary_accuracy: 0.5910 - loss: 86485.8641

263/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5912 - loss: 86222.0573

268/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5914 - loss: 85971.3163

274/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5917 - loss: 85675.7594

279/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5920 - loss: 85428.2910

285/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5923 - loss: 85138.1435

291/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5925 - loss: 84867.9320

295/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5927 - loss: 84691.7318

301/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5930 - loss: 84423.6440

307/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5932 - loss: 84162.4587

313/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5935 - loss: 83904.5556

318/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5937 - loss: 83685.1585

324/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5940 - loss: 83415.8709

329/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5942 - loss: 83201.9504

333/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5944 - loss: 83031.9303

338/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5946 - loss: 82811.9478

343/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5948 - loss: 82588.4724

348/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5950 - loss: 82363.5613

353/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5952 - loss: 82143.6545

358/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5954 - loss: 81923.4934

363/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5956 - loss: 81708.8697

368/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5958 - loss: 81491.9894

373/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5960 - loss: 81273.4140

378/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5962 - loss: 81057.0677

384/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5965 - loss: 80793.9334

389/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5967 - loss: 80572.9640

394/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5969 - loss: 80352.5822

399/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5971 - loss: 80132.4238

404/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5974 - loss: 79916.7096

409/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5976 - loss: 79698.9561

414/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5978 - loss: 79479.1016

418/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5979 - loss: 79303.9757

423/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5981 - loss: 79085.2845

428/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5983 - loss: 78864.9403

433/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5986 - loss: 78644.0415

439/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5988 - loss: 78381.0330

445/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5990 - loss: 78127.7525

450/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5992 - loss: 77918.3179

455/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5994 - loss: 77709.9624

460/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5014 - binary_accuracy: 0.5996 - loss: 77502.2361

465/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5013 - binary_accuracy: 0.5998 - loss: 77297.3054

471/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5013 - binary_accuracy: 0.6000 - loss: 77053.7966

477/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5013 - binary_accuracy: 0.6003 - loss: 76807.9695

483/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5013 - binary_accuracy: 0.6005 - loss: 76560.9517

488/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5013 - binary_accuracy: 0.6007 - loss: 76356.6514

493/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5012 - binary_accuracy: 0.6009 - loss: 76151.8857

497/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.5012 - binary_accuracy: 0.6010 - loss: 75987.4424

500/500 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - auc: 0.5003 - binary_accuracy: 0.6199 - loss: 55291.3125 - val_auc: 0.5000 - val_binary_accuracy: 0.6928 - val_loss: 0.6430

Epoch 3/10

  1/500 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - auc: 0.4789 - binary_accuracy: 0.6719 - loss: 79719.8281

  6/500 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - auc: 0.5110 - binary_accuracy: 0.6349 - loss: 40312.2207

 11/500 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - auc: 0.5079 - binary_accuracy: 0.6424 - loss: 35814.6864

2026-05-31 11:00:28.121802: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

 16/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5037 - binary_accuracy: 0.6486 - loss: 36312.5824

 21/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5029 - binary_accuracy: 0.6531 - loss: 36830.7711

 27/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5025 - binary_accuracy: 0.6574 - loss: 36211.8526

 33/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5006 - binary_accuracy: 0.6589 - loss: 35689.2914

 38/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4993 - binary_accuracy: 0.6588 - loss: 35613.7632

 43/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4983 - binary_accuracy: 0.6589 - loss: 35505.2065

 48/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4977 - binary_accuracy: 0.6593 - loss: 35051.8106

 54/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4968 - binary_accuracy: 0.6592 - loss: 34325.1558

 59/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4962 - binary_accuracy: 0.6593 - loss: 33649.6227

 64/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4959 - binary_accuracy: 0.6593 - loss: 32955.1105

 68/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4956 - binary_accuracy: 0.6593 - loss: 32405.5754

 72/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4955 - binary_accuracy: 0.6594 - loss: 31887.1745

 76/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4954 - binary_accuracy: 0.6595 - loss: 31457.4689

 80/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4954 - binary_accuracy: 0.6596 - loss: 31033.8346

 85/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4953 - binary_accuracy: 0.6597 - loss: 30513.5330

 90/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4952 - binary_accuracy: 0.6597 - loss: 30034.4776

 94/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4951 - binary_accuracy: 0.6597 - loss: 29754.7786

 99/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4951 - binary_accuracy: 0.6597 - loss: 29426.1809

104/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4952 - binary_accuracy: 0.6599 - loss: 29086.5847

109/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4953 - binary_accuracy: 0.6600 - loss: 28750.0646

115/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4953 - binary_accuracy: 0.6600 - loss: 28398.8842

120/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4952 - binary_accuracy: 0.6599 - loss: 28096.9553

125/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4951 - binary_accuracy: 0.6599 - loss: 27797.5494

131/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4950 - binary_accuracy: 0.6598 - loss: 27449.5028

136/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4949 - binary_accuracy: 0.6597 - loss: 27154.3206

141/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6596 - loss: 26881.8278

146/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6596 - loss: 26655.4339

152/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6596 - loss: 26458.3743

157/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6595 - loss: 26322.5030

163/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6595 - loss: 26150.3753

168/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6595 - loss: 26002.2496

173/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4948 - binary_accuracy: 0.6595 - loss: 25852.9737

178/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4949 - binary_accuracy: 0.6595 - loss: 25709.6852

183/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4950 - binary_accuracy: 0.6595 - loss: 25563.8578

188/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4951 - binary_accuracy: 0.6595 - loss: 25428.3978

192/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4952 - binary_accuracy: 0.6596 - loss: 25337.5563

197/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4952 - binary_accuracy: 0.6596 - loss: 25218.1356

202/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4953 - binary_accuracy: 0.6596 - loss: 25092.2606

208/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4954 - binary_accuracy: 0.6596 - loss: 24941.5884

213/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4955 - binary_accuracy: 0.6596 - loss: 24820.2434

218/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4956 - binary_accuracy: 0.6596 - loss: 24694.4502

224/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4958 - binary_accuracy: 0.6597 - loss: 24542.8962

229/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4959 - binary_accuracy: 0.6597 - loss: 24415.7449

234/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4960 - binary_accuracy: 0.6598 - loss: 24285.5952

240/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4962 - binary_accuracy: 0.6598 - loss: 24127.5267

245/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4963 - binary_accuracy: 0.6599 - loss: 23995.5119

250/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4964 - binary_accuracy: 0.6600 - loss: 23861.8067

255/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4966 - binary_accuracy: 0.6600 - loss: 23728.2994

260/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4967 - binary_accuracy: 0.6601 - loss: 23595.4014

265/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4968 - binary_accuracy: 0.6601 - loss: 23461.8253

271/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4969 - binary_accuracy: 0.6602 - loss: 23301.4464

276/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4970 - binary_accuracy: 0.6602 - loss: 23168.2243

281/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4971 - binary_accuracy: 0.6603 - loss: 23039.3699

286/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4972 - binary_accuracy: 0.6603 - loss: 22913.2090

292/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4973 - binary_accuracy: 0.6603 - loss: 22763.8216

297/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4973 - binary_accuracy: 0.6604 - loss: 22647.4116

302/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4974 - binary_accuracy: 0.6604 - loss: 22531.3127

306/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4974 - binary_accuracy: 0.6604 - loss: 22439.3593

311/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6604 - loss: 22325.2994

316/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6605 - loss: 22224.7626

321/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6605 - loss: 22128.0264

327/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6605 - loss: 22011.2452

333/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6605 - loss: 21894.6540

339/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4975 - binary_accuracy: 0.6605 - loss: 21780.2591

343/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4976 - binary_accuracy: 0.6605 - loss: 21705.8595

348/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4976 - binary_accuracy: 0.6606 - loss: 21612.7334

353/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4976 - binary_accuracy: 0.6606 - loss: 21519.3020

359/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4976 - binary_accuracy: 0.6606 - loss: 21406.9118

364/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4976 - binary_accuracy: 0.6606 - loss: 21313.1165

370/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6606 - loss: 21202.0434

375/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6607 - loss: 21112.7331

380/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6607 - loss: 21023.7482

385/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6607 - loss: 20935.2305

390/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6607 - loss: 20848.1009

395/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6607 - loss: 20766.5876

400/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6608 - loss: 20688.9153

405/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4977 - binary_accuracy: 0.6608 - loss: 20611.2301

410/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6608 - loss: 20534.5072

415/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6608 - loss: 20465.7842

421/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6609 - loss: 20387.6343

426/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6609 - loss: 20323.7494

431/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6609 - loss: 20259.9848

436/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6610 - loss: 20196.8699

441/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6610 - loss: 20134.6838

446/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6610 - loss: 20072.7091

450/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6610 - loss: 20023.1613

455/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6611 - loss: 19961.8988

460/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6611 - loss: 19900.7236

465/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6611 - loss: 19839.2499

470/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4981 - binary_accuracy: 0.6612 - loss: 19777.9123

475/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4981 - binary_accuracy: 0.6612 - loss: 19717.5063

480/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4981 - binary_accuracy: 0.6612 - loss: 19657.2272

485/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4982 - binary_accuracy: 0.6613 - loss: 19598.6964

490/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4982 - binary_accuracy: 0.6613 - loss: 19540.2543

495/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4982 - binary_accuracy: 0.6613 - loss: 19484.0950

2026-05-31 11:00:33.871514: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

500/500 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - auc: 0.5018 - binary_accuracy: 0.6648 - loss: 14097.9473 - val_auc: 0.5000 - val_binary_accuracy: 0.6928 - val_loss: 0.6239

Epoch 4/10

  1/500 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - auc: 0.5719 - binary_accuracy: 0.7188 - loss: 166.9604

  6/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5566 - binary_accuracy: 0.7124 - loss: 293.0935

 11/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5457 - binary_accuracy: 0.6936 - loss: 378.1185

 16/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5377 - binary_accuracy: 0.6848 - loss: 390.9494

 21/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5319 - binary_accuracy: 0.6805 - loss: 1131.0641

 26/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.5283 - binary_accuracy: 0.6769 - loss: 1650.7138

 32/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5278 - binary_accuracy: 0.6752 - loss: 1963.3566

 38/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5277 - binary_accuracy: 0.6746 - loss: 2182.1738

 43/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5270 - binary_accuracy: 0.6739 - loss: 2272.7605

 47/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5264 - binary_accuracy: 0.6735 - loss: 2312.8684

 53/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5257 - binary_accuracy: 0.6733 - loss: 2528.3046

 57/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5252 - binary_accuracy: 0.6733 - loss: 2738.8294

 63/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5243 - binary_accuracy: 0.6731 - loss: 3044.2641

 68/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5234 - binary_accuracy: 0.6728 - loss: 3369.1062

 73/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5226 - binary_accuracy: 0.6725 - loss: 3628.8069

 79/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5217 - binary_accuracy: 0.6721 - loss: 3861.9444

 85/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5209 - binary_accuracy: 0.6718 - loss: 4104.4569

 90/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5203 - binary_accuracy: 0.6716 - loss: 4269.9503

 96/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5196 - binary_accuracy: 0.6714 - loss: 4505.7459

101/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5192 - binary_accuracy: 0.6712 - loss: 4697.9014

106/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5187 - binary_accuracy: 0.6711 - loss: 4897.1915

112/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5181 - binary_accuracy: 0.6708 - loss: 5138.8704

117/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5176 - binary_accuracy: 0.6707 - loss: 5314.5825

122/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5172 - binary_accuracy: 0.6706 - loss: 5460.8828

127/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5168 - binary_accuracy: 0.6705 - loss: 5592.0321

133/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5162 - binary_accuracy: 0.6703 - loss: 5721.9199

139/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5157 - binary_accuracy: 0.6702 - loss: 5825.6474

144/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5153 - binary_accuracy: 0.6700 - loss: 5899.6205

149/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5149 - binary_accuracy: 0.6699 - loss: 5963.7428

154/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5146 - binary_accuracy: 0.6698 - loss: 6028.4542

159/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5142 - binary_accuracy: 0.6698 - loss: 6093.2742

164/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5139 - binary_accuracy: 0.6697 - loss: 6146.8154

169/500 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - auc: 0.5136 - binary_accuracy: 0.6696 - loss: 6190.6493

174/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5133 - binary_accuracy: 0.6695 - loss: 6229.6669

179/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5129 - binary_accuracy: 0.6694 - loss: 6265.9990

184/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5127 - binary_accuracy: 0.6694 - loss: 6299.0962

188/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5125 - binary_accuracy: 0.6693 - loss: 6326.4118

192/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5123 - binary_accuracy: 0.6693 - loss: 6349.9192

197/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5121 - binary_accuracy: 0.6693 - loss: 6375.2017

202/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5119 - binary_accuracy: 0.6692 - loss: 6404.0657

207/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5117 - binary_accuracy: 0.6692 - loss: 6431.9113

212/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5115 - binary_accuracy: 0.6692 - loss: 6455.7432

217/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.5113 - binary_accuracy: 0.6692 - loss: 6475.0870

222/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5112 - binary_accuracy: 0.6692 - loss: 6489.9214

228/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5110 - binary_accuracy: 0.6692 - loss: 6502.8553

234/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5107 - binary_accuracy: 0.6691 - loss: 6510.6223

240/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5105 - binary_accuracy: 0.6691 - loss: 6526.3043

245/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5103 - binary_accuracy: 0.6691 - loss: 6537.5304

249/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5102 - binary_accuracy: 0.6691 - loss: 6544.2007

255/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5100 - binary_accuracy: 0.6690 - loss: 6550.8616

260/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5099 - binary_accuracy: 0.6690 - loss: 6553.6722

266/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5097 - binary_accuracy: 0.6690 - loss: 6555.3921

271/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5096 - binary_accuracy: 0.6690 - loss: 6554.5274

276/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5095 - binary_accuracy: 0.6690 - loss: 6551.8668

282/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5094 - binary_accuracy: 0.6690 - loss: 6546.4095

287/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5093 - binary_accuracy: 0.6691 - loss: 6545.4676

292/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5092 - binary_accuracy: 0.6691 - loss: 6542.8254

298/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5091 - binary_accuracy: 0.6691 - loss: 6537.5288

305/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5090 - binary_accuracy: 0.6691 - loss: 6528.6124

310/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.5089 - binary_accuracy: 0.6691 - loss: 6520.6045

315/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5088 - binary_accuracy: 0.6691 - loss: 6511.3535

320/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5087 - binary_accuracy: 0.6691 - loss: 6500.9788

326/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5087 - binary_accuracy: 0.6691 - loss: 6487.2397

332/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5085 - binary_accuracy: 0.6691 - loss: 6472.4881

337/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5084 - binary_accuracy: 0.6691 - loss: 6459.4355

344/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5083 - binary_accuracy: 0.6691 - loss: 6439.9918

350/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5082 - binary_accuracy: 0.6691 - loss: 6423.6781

355/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5081 - binary_accuracy: 0.6691 - loss: 6409.6085

359/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5080 - binary_accuracy: 0.6691 - loss: 6398.8856

365/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.5079 - binary_accuracy: 0.6691 - loss: 6382.2458

2026-05-31 11:00:38.116431: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

500/500 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - auc: 0.5003 - binary_accuracy: 0.6681 - loss: 5328.5703 - val_auc: 0.5000 - val_binary_accuracy: 0.6928 - val_loss: 0.6193

Epoch 5/10

2026-05-31 11:00:38.424979: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

  1/500 ━━━━━━━━━━━━━━━━━━━━ 2:33:34 18s/step - auc: 0.4591 - binary_accuracy: 0.6875 - loss: 287.8694

  6/500 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - auc: 0.4923 - binary_accuracy: 0.6783 - loss: 251.9132

 12/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4976 - binary_accuracy: 0.6851 - loss: 300.2879

 17/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4974 - binary_accuracy: 0.6826 - loss: 619.1885

 23/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4981 - binary_accuracy: 0.6813 - loss: 883.4523

 28/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.4992 - binary_accuracy: 0.6815 - loss: 979.8390

 33/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5003 - binary_accuracy: 0.6815 - loss: 1018.7612

 38/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5015 - binary_accuracy: 0.6819 - loss: 1028.2547

 43/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5023 - binary_accuracy: 0.6820 - loss: 1067.4531

 49/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5030 - binary_accuracy: 0.6820 - loss: 1166.6637

 54/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5035 - binary_accuracy: 0.6822 - loss: 1260.5300

 59/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5033 - binary_accuracy: 0.6823 - loss: 1330.5482

 64/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5025 - binary_accuracy: 0.6821 - loss: 1400.7802

 68/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5020 - binary_accuracy: 0.6818 - loss: 1441.5458

 74/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5017 - binary_accuracy: 0.6819 - loss: 1484.8610

 79/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5016 - binary_accuracy: 0.6819 - loss: 1508.4436

 85/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5014 - binary_accuracy: 0.6819 - loss: 1526.0446

 91/500 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - auc: 0.5011 - binary_accuracy: 0.6818 - loss: 1544.8532

 96/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5009 - binary_accuracy: 0.6817 - loss: 1618.1805

101/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5008 - binary_accuracy: 0.6816 - loss: 1723.1201

106/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5006 - binary_accuracy: 0.6815 - loss: 1818.8853

109/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5005 - binary_accuracy: 0.6814 - loss: 1868.5458

113/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5004 - binary_accuracy: 0.6813 - loss: 1926.9496

118/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5003 - binary_accuracy: 0.6813 - loss: 2009.7802

123/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.5001 - binary_accuracy: 0.6811 - loss: 2079.7714

129/500 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - auc: 0.4998 - binary_accuracy: 0.6809 - loss: 2153.2898

135/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4996 - binary_accuracy: 0.6806 - loss: 2217.6554

139/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4995 - binary_accuracy: 0.6805 - loss: 2255.2865

144/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4993 - binary_accuracy: 0.6802 - loss: 2347.1000

147/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6801 - loss: 2409.1680

152/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6798 - loss: 2504.7090

156/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4988 - binary_accuracy: 0.6796 - loss: 2573.1536

161/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4987 - binary_accuracy: 0.6793 - loss: 2652.1046

166/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4985 - binary_accuracy: 0.6791 - loss: 2722.5524

171/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4984 - binary_accuracy: 0.6788 - loss: 2791.7721

176/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4982 - binary_accuracy: 0.6786 - loss: 2861.3287

181/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4981 - binary_accuracy: 0.6784 - loss: 2930.7281

186/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6782 - loss: 2993.0585

191/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6781 - loss: 3048.8903

196/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6780 - loss: 3098.8117

201/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6779 - loss: 3143.3912

206/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6778 - loss: 3183.1092

210/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6777 - loss: 3211.7942

215/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6776 - loss: 3244.4619

220/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6775 - loss: 3274.9358

226/500 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.4978 - binary_accuracy: 0.6774 - loss: 3307.4860

232/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4979 - binary_accuracy: 0.6774 - loss: 3336.9869

238/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4980 - binary_accuracy: 0.6773 - loss: 3363.6775

243/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4982 - binary_accuracy: 0.6773 - loss: 3382.8878

250/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4983 - binary_accuracy: 0.6773 - loss: 3408.3813

255/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4984 - binary_accuracy: 0.6772 - loss: 3428.2038

261/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4985 - binary_accuracy: 0.6772 - loss: 3452.2874

267/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4986 - binary_accuracy: 0.6772 - loss: 3473.3768

274/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4986 - binary_accuracy: 0.6771 - loss: 3494.5419

280/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4987 - binary_accuracy: 0.6771 - loss: 3511.0839

286/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4988 - binary_accuracy: 0.6771 - loss: 3526.3045

291/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4989 - binary_accuracy: 0.6770 - loss: 3539.1954

295/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4989 - binary_accuracy: 0.6770 - loss: 3548.6216

301/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6770 - loss: 3561.8682

307/500 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6769 - loss: 3573.9177

313/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6769 - loss: 3586.1504

318/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6769 - loss: 3596.2077

324/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6768 - loss: 3606.6470

329/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6768 - loss: 3614.0474

334/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6768 - loss: 3621.3599

339/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6767 - loss: 3631.3668

344/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6767 - loss: 3640.2298

349/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6767 - loss: 3648.0151

355/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6766 - loss: 3656.0533

360/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6766 - loss: 3662.9000

365/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6765 - loss: 3673.9231

371/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6764 - loss: 3687.0135

376/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6764 - loss: 3698.1799

382/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6763 - loss: 3710.8557

387/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6763 - loss: 3720.8646

393/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6762 - loss: 3732.8166

398/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6762 - loss: 3741.7727

404/500 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6761 - loss: 3751.6126

409/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6761 - loss: 3759.7053

412/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6760 - loss: 3764.1786

417/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6760 - loss: 3771.0370

422/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6760 - loss: 3777.1380

427/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6759 - loss: 3782.5534

432/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6759 - loss: 3787.3640

438/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4990 - binary_accuracy: 0.6759 - loss: 3792.5247

442/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6759 - loss: 3796.0642

447/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6758 - loss: 3800.6166

452/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6758 - loss: 3804.6531

458/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6758 - loss: 3808.8941

462/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6758 - loss: 3811.3743

467/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6758 - loss: 3814.0388

472/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6757 - loss: 3816.2220

477/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6757 - loss: 3817.9369

482/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4991 - binary_accuracy: 0.6757 - loss: 3819.2427

487/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6757 - loss: 3820.1325

492/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6757 - loss: 3820.8130

497/500 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - auc: 0.4992 - binary_accuracy: 0.6756 - loss: 3821.2160

2026-05-31 11:01:02.672101: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node IteratorGetNext}}]]

500/500 ━━━━━━━━━━━━━━━━━━━━ 25s 12ms/step - auc: 0.5001 - binary_accuracy: 0.6740 - loss: 3822.7427 - val_auc: 0.5000 - val_binary_accuracy: 0.6928 - val_loss: 0.6174

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:struct2tensor is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_decision_forests is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:tensorflow_text is not available.

INFO:tensorflow:Assets written to: /home/user/chicago-taxi-mlops/output/pipeline_root/Trainer/model/74/Format-Serving/assets

INFO:tensorflow:Assets written to: /home/user/chicago-taxi-mlops/output/pipeline_root/Trainer/model/74/Format-Serving/assets

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

WARNING:absl:ArtifactQuery.property_predicate is not supported.

WARNING:absl:ArtifactQuery.property_predicate is not supported.

Pipeline execution completed!
CPU times: user 2min 35s, sys: 9.31 s, total: 2min 45s
Wall time: 3min 37s

## 7. Evaluasi Hasil Pipeline

In [8]:
output_dir = "output"
if os.path.exists(output_dir):
    print("Pipeline output directories:")
    for root, dirs, files in os.walk(output_dir):
        level = root.replace(output_dir, "").count(os.sep)
        indent = " " * 2 * level
        print(f"{indent}{os.path.basename(root)}/")
        subindent = " " * 2 * (level + 1)
        for file in files[:5]:
            print(f"{subindent}{file}")
else:
    print("Output directory not found.")

Pipeline output directories:
output/
  metadata.sqlite
  pipeline_root/
    ExampleValidator/
      anomalies/
        51/
          Split-eval/
            SchemaDiff.pb
          Split-train/
            SchemaDiff.pb
        61/
          Split-eval/
            SchemaDiff.pb
          Split-train/
            SchemaDiff.pb
        71/
          Split-eval/
            SchemaDiff.pb
          Split-train/
            SchemaDiff.pb
        5/
          Split-eval/
            SchemaDiff.pb
          Split-train/
            SchemaDiff.pb
        41/
          Split-eval/
            SchemaDiff.pb
          Split-train/
            SchemaDiff.pb
      .system/
        stateful_working_dir/
        executor_execution/
          51/
          61/
          71/
          5/
          41/
    StatisticsGen/
      statistics/
        49/
          Split-eval/
            FeatureStats.pb
          Split-train/
            FeatureStats.pb
        3/
          Split-eval/
            FeatureStats.pb
          Split-train/
            FeatureStats.pb
        69/
          Split-eval/
            FeatureStats.pb
          Split-train/
            FeatureStats.pb
        39/
          Split-eval/
            FeatureStats.pb
          Split-train/
            FeatureStats.pb
        59/
          Split-eval/
            FeatureStats.pb
          Split-train/
            FeatureStats.pb
      .system/
        stateful_working_dir/
        executor_execution/
          49/
          3/
          69/
          39/
          59/
    SchemaGen/
      schema/
        50/
          schema.pbtxt
        40/
          schema.pbtxt
        60/
          schema.pbtxt
        4/
          schema.pbtxt
        70/
          schema.pbtxt
      .system/
        stateful_working_dir/
        executor_execution/
          50/
          40/
          60/
          4/
          70/
    Evaluator/
      evaluation/
        35/
          validations.tfrecord
          metrics-00000-of-00001.tfrecord
          eval_config.json
          plots-00000-of-00001.tfrecord
          attributions-00000-of-00001.tfrecord
        75/
          validations.tfrecord
          metrics-00000-of-00001.tfrecord
          eval_config.json
          plots-00000-of-00001.tfrecord
          attributions-00000-of-00001.tfrecord
        45/
          validations.tfrecord
          metrics-00000-of-00001.tfrecord
          eval_config.json
          plots-00000-of-00001.tfrecord
          attributions-00000-of-00001.tfrecord
        65/
          validations.tfrecord
          metrics-00000-of-00001.tfrecord
          eval_config.json
          plots-00000-of-00001.tfrecord
          attributions-00000-of-00001.tfrecord
        55/
          validations.tfrecord
          metrics-00000-of-00001.tfrecord
          eval_config.json
          plots-00000-of-00001.tfrecord
          attributions-00000-of-00001.tfrecord
      blessing/
        35/
        75/
        45/
        65/
        55/
      .system/
        stateful_working_dir/
          bc7a9423-e7a9-491b-9aff-f86a0b5e414b/
          eae3e1d1-e928-434c-afad-93bf1c5ce5a4/
        executor_execution/
          35/
          26/
          75/
          45/
          65/
          55/
          17/
    Trainer/
      model/
        16/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
        64/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
        74/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
        44/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
        34/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
        54/
          Format-Serving/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
      model_run/
        16/
          validation/
            events.out.tfevents.1780209257.tfx-worker.26175.1.v2
          train/
            events.out.tfevents.1780209251.tfx-worker.26175.0.v2
        64/
          validation/
            events.out.tfevents.1780224774.tfx-worker.36284.1.v2
          train/
            events.out.tfevents.1780224763.tfx-worker.36284.0.v2
        74/
          validation/
            events.out.tfevents.1780225221.tfx-worker.38313.1.v2
          train/
            events.out.tfevents.1780225211.tfx-worker.38313.0.v2
        44/
          validation/
            events.out.tfevents.1780217815.tfx-worker.30549.1.v2
          train/
            events.out.tfevents.1780217808.tfx-worker.30549.0.v2
        34/
          validation/
            events.out.tfevents.1780211920.tfx-worker.27890.1.v2
          train/
            events.out.tfevents.1780211913.tfx-worker.27890.0.v2
        54/
          validation/
            events.out.tfevents.1780224576.tfx-worker.34486.1.v2
          train/
            events.out.tfevents.1780224567.tfx-worker.34486.0.v2
      .system/
        stateful_working_dir/
          fb5a7c90-d7f0-44d5-84d7-18ddefc6e38e/
        executor_execution/
          16/
          64/
          74/
          44/
          8/
          34/
          54/
    Transform/
      transformed_examples/
        72/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        14/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        52/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        42/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        6/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        32/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
        62/
          Split-eval/
            transformed_examples-00000-of-00001.gz
          Split-train/
            transformed_examples-00000-of-00001.gz
      transform_graph/
        72/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        14/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        52/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        42/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        6/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        32/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
        62/
          metadata/
            schema.pbtxt
          transform_fn/
            saved_model.pb
            fingerprint.pb
            assets/
              payment_type_xf
              company_xf
            variables/
              variables.data-00000-of-00001
              variables.index
          transformed_metadata/
            asset_map
            schema.pbtxt
      post_transform_anomalies/
        72/
          SchemaDiff.pb
        14/
          SchemaDiff.pb
        52/
          SchemaDiff.pb
        42/
          SchemaDiff.pb
        6/
          SchemaDiff.pb
        32/
          SchemaDiff.pb
        62/
          SchemaDiff.pb
      post_transform_stats/
        72/
          FeatureStats.pb
        14/
          FeatureStats.pb
        52/
          FeatureStats.pb
        42/
          FeatureStats.pb
        6/
          FeatureStats.pb
        32/
          FeatureStats.pb
        62/
          FeatureStats.pb
      updated_analyzer_cache/
        72/
          pipeline_root-ImportExampleGen-examples-67-Split-train-STAR-8f6a0467726a13d5571e9dacafa34b9e3cbed1bb3b0d9fe6a3cc171334535b03/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        14/
          pipeline_root-ImportExampleGen-examples-1-Split-train-STAR-3c085995fc428f09532306787bea954928ae3e6c3f885987cb37f1be8cdf3d28/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        52/
          pipeline_root-ImportExampleGen-examples-47-Split-train-STAR-44c0ceac5c3e8305b4dea1a40c6745935a9964319ed03cf4f939f76e44752e24/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        42/
          pipeline_root-ImportExampleGen-examples-37-Split-train-STAR-d38d4c7aef131c120e252b28377d36934765d30bae96eeed9884cad6d317b9ef/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        6/
          pipeline_root-ImportExampleGen-examples-1-Split-train-STAR-3c085995fc428f09532306787bea954928ae3e6c3f885987cb37f1be8cdf3d28/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        32/
          pipeline_root-ImportExampleGen-examples-1-Split-train-STAR-3c085995fc428f09532306787bea954928ae3e6c3f885987cb37f1be8cdf3d28/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
        62/
          pipeline_root-ImportExampleGen-examples-57-Split-train-STAR-17146e6f4b343dc48e5674743173e58a8ef7f79e298acab92a56c7138634b928/
            MANIFEST
            METADATA-00000-of-00001
            0-00000-of-00001.gz
            1-00000-of-00001.gz
      pre_transform_schema/
        72/
          schema.pbtxt
        14/
          schema.pbtxt
        52/
          schema.pbtxt
        42/
          schema.pbtxt
        6/
          schema.pbtxt
        32/
          schema.pbtxt
        62/
          schema.pbtxt
      post_transform_schema/
        72/
          schema.pbtxt
        14/
          schema.pbtxt
        52/
          schema.pbtxt
        42/
          schema.pbtxt
        6/
          schema.pbtxt
        32/
          schema.pbtxt
        62/
          schema.pbtxt
      pre_transform_stats/
        72/
          FeatureStats.pb
        14/
          FeatureStats.pb
        52/
          FeatureStats.pb
        42/
          FeatureStats.pb
        6/
          FeatureStats.pb
        32/
          FeatureStats.pb
        62/
          FeatureStats.pb
      .system/
        stateful_working_dir/
        executor_execution/
          72/
          14/
          52/
          42/
          6/
          32/
          62/
    ImportExampleGen/
      examples/
        1/
          Split-eval/
            data_tfrecord-00000-of-00001.gz
          Split-train/
            data_tfrecord-00000-of-00001.gz
        37/
          Split-eval/
            data_tfrecord-00000-of-00001.gz
          Split-train/
            data_tfrecord-00000-of-00001.gz
        67/
          Split-eval/
            data_tfrecord-00000-of-00001.gz
          Split-train/
            data_tfrecord-00000-of-00001.gz
        57/
          Split-eval/
            data_tfrecord-00000-of-00001.gz
          Split-train/
            data_tfrecord-00000-of-00001.gz
        47/
          Split-eval/
            data_tfrecord-00000-of-00001.gz
          Split-train/
            data_tfrecord-00000-of-00001.gz
      .system/
        stateful_working_dir/
        executor_execution/
          1/
          37/
          67/
          57/
          47/
        driver_execution/
          1780224463338915/
          1780207189046217/
          1780225081921303/
          1780211841293684/
          1780210562266298/
          1780224649212684/
          1780217698440897/
          1780209180473324/
    Tuner/
      best_hyperparameters/
        53/
          best_hyperparameters.txt
        15/
          best_hyperparameters.txt
        43/
          best_hyperparameters.txt
        7/
          best_hyperparameters.txt
        33/
          best_hyperparameters.txt
        63/
          best_hyperparameters.txt
        73/
          best_hyperparameters.txt
      tuner_results/
        53/
          tuner_results.json
        15/
          tuner_results.json
        43/
          tuner_results.json
        7/
          tuner_results.json
        33/
          tuner_results.json
        63/
          tuner_results.json
        73/
          tuner_results.json
      .system/
        stateful_working_dir/
        executor_execution/
          53/
          15/
          43/
          7/
          33/
          63/
          73/
    Pusher/
      pushed_model/
        76/
        56/
        46/
        36/
        66/
      .system/
        stateful_working_dir/
        executor_execution/
          76/
          56/
          46/
          36/
          66/
    _wheels/
      tfx_user_code_transform-0.0+9ce7107b01410c5b84004ec5dfc6697c8e3446acf24b8eecd2fe598b8e170ee5-py3-none-any.whl
      tfx_user_code_trainer-0.0+20d78c0fb212cce0d5a9090552cac3345f114dadf332723c758c87b8d714da65-py3-none-any.whl
      tfx_user_code_trainer-0.0+11c5a534d20deec8d3e45d94a94f7c55afa102c2f915ef00f422b2312ffd3426-py3-none-any.whl
      tfx_user_code_tuner-0.0+9ce7107b01410c5b84004ec5dfc6697c8e3446acf24b8eecd2fe598b8e170ee5-py3-none-any.whl
      tfx_user_code_trainer-0.0+9ce7107b01410c5b84004ec5dfc6697c8e3446acf24b8eecd2fe598b8e170ee5-py3-none-any.whl

In [9]:
serving_model_dir = "serving_model"
if os.path.exists(serving_model_dir):
    saved_models = [
        d for d in os.listdir(serving_model_dir) 
        if os.path.isdir(os.path.join(serving_model_dir, d))
    ]
    print(f"Saved models: {saved_models}")
    if saved_models:
        latest = max(saved_models, key=lambda d: os.path.getmtime(
            os.path.join(serving_model_dir, d)
        ))
        print(f"Latest model: {latest}")
else:
    print("Serving model directory not found.")

Serving model directory not found.

## 8. Performa Model

Model yang dihasilkan dievaluasi menggunakan metrik:
- **Binary Accuracy**: Mengukur persentase prediksi yang benar
- **AUC**: Mengukur kemampuan model membedakan kelas positif dan negatif
- **Precision**: Proporsi prediksi positif yang benar
- **Recall**: Proporsi data positif yang berhasil dideteksi

Model yang memenuhi threshold evaluasi akan dianggap "blessed" dan siap di-push ke serving.

## 9. Model Deployment

Model akan di-deploy menggunakan **Docker** dan dijalankan di platform **Railway** (cloud).

### Opsi Deployment:
- **Railway**: Platform cloud yang mudah digunakan
- **Docker**: Containerization untuk konsistensi environment
- **Flask API**: REST API untuk model serving

### Langkah Deployment:
1. Build Docker image
2. Push image ke Railway
3. Jalankan container dengan exposed port 8080

### Endpoint API:
- `GET /` - Health check
- `GET /v1/models/taxi-model` - Informasi model
- `POST /v1/models/taxi-model:predict` - Prediksi

## 10. Monitoring dengan Prometheus

Sistem monitoring diimplementasikan menggunakan **Prometheus** dengan metrik:
- Request count
- Request latency
- Prediction distribution
- System resource usage

### Konfigurasi Monitoring:
- Prometheus container berjalan dengan port 9090
- Scrape interval: 10 detik
- Target: Aplikasi ML serving (port 8080)

## 10. Prediksi dengan TF Serving

Setelah model berhasil di-deploy ke Railway menggunakan TF Serving, kita dapat melakukan prediksi dengan mengirim request ke endpoint TF Serving.

Model menggunakan input serialized **tf.Example** yang di-encode ke base64, sesuai format standar TF Serving.

In [8]:
import base64
import requests
import tensorflow as tf

# URL TF Serving di Railway
TF_SERVING_URL = "https://chicago-taxi-mlops-production.up.railway.app"

# Sample 1: Perjalanan dengan Credit Card (expected: high probability of tip)
feature_cc = {
    "trip_miles": tf.train.Feature(float_list=tf.train.FloatList(value=[2.5])),
    "fare": tf.train.Feature(float_list=tf.train.FloatList(value=[8.5])),
    "trip_seconds": tf.train.Feature(int64_list=tf.train.Int64List(value=[600])),
    "trip_start_timestamp": tf.train.Feature(int64_list=tf.train.Int64List(value=[1437076800])),
    "payment_type": tf.train.Feature(bytes_list=tf.train.BytesList(value=[b"Credit Card"])),
    "company": tf.train.Feature(bytes_list=tf.train.BytesList(value=[b"Taxi Affiliation Services"])),
    "trip_start_hour": tf.train.Feature(int64_list=tf.train.Int64List(value=[14])),
    "trip_start_day": tf.train.Feature(int64_list=tf.train.Int64List(value=[3])),
    "trip_start_month": tf.train.Feature(int64_list=tf.train.Int64List(value=[5])),
}
example_cc = tf.train.Example(features=tf.train.Features(feature=feature_cc))
serialized_cc = base64.b64encode(example_cc.SerializeToString()).decode("utf-8")

# Sample 2: Perjalanan dengan Cash (expected: lower probability of tip)
feature_cash = {
    "trip_miles": tf.train.Feature(float_list=tf.train.FloatList(value=[1.2])),
    "fare": tf.train.Feature(float_list=tf.train.FloatList(value=[5.85])),
    "trip_seconds": tf.train.Feature(int64_list=tf.train.Int64List(value=[180])),
    "trip_start_timestamp": tf.train.Feature(int64_list=tf.train.Int64List(value=[1382319000])),
    "payment_type": tf.train.Feature(bytes_list=tf.train.BytesList(value=[b"Cash"])),
    "company": tf.train.Feature(bytes_list=tf.train.BytesList(value=[b"Taxi Affiliation Services"])),
    "trip_start_hour": tf.train.Feature(int64_list=tf.train.Int64List(value=[1])),
    "trip_start_day": tf.train.Feature(int64_list=tf.train.Int64List(value=[2])),
    "trip_start_month": tf.train.Feature(int64_list=tf.train.Int64List(value=[10])),
}
example_cash = tf.train.Example(features=tf.train.Features(feature=feature_cash))
serialized_cash = base64.b64encode(example_cash.SerializeToString()).decode("utf-8")

payload = {"instances": [
    {"examples": {"b64": serialized_cc}},
    {"examples": {"b64": serialized_cash}},
]}

print("Sending prediction request...")
response = requests.post(
    f"{TF_SERVING_URL}/v1/models/taxi-model:predict",
    json=payload
)
print(f"Status: {response.status_code}")
if response.status_code == 200:
    result = response.json()
    print(f"Result: {result}")
    for i, pred in enumerate(result["predictions"]):
        prob = pred[0]
        print(f"Sample {i+1}: probability={prob:.4f}, prediction={1 if prob > 0.5 else 0}")
else:
    print(f"Error: {response.text}")

Sending prediction request...
Status: 200
Result: {'predictions': [[0.984453082], [0.0175342243]]}
Sample 1: probability=0.9845, prediction=1
Sample 2: probability=0.0175, prediction=0

## 11. Kesimpulan

Proyek ini berhasil mengimplementasikan **MLOps pipeline end-to-end** menggunakan:
1. **TFX** untuk membangun pipeline machine learning yang terstruktur
2. **Apache Beam** sebagai pipeline orchestrator
3. **Docker** untuk containerization
4. **Railway** sebagai cloud platform
5. **Prometheus** untuk monitoring sistem

Dengan pipeline ini, proses pengembangan dan pengoperasian model machine learning dapat dilakukan secara otomatis, terukur, dan mudah dimonitoring.